version: "3.2"
services:

  php:
    build: './php/'
    container_name: 'php'
    networks:
      - backend
    volumes:
      - ./../bbpl:/var/www/html/

  apache:
    build: './apache/'
    container_name: 'apache'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./../bbpl:/var/www/html/

  mysql:
    image: mariadb:latest
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=bbpl_payments
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/dbdata:/var/lib/mariadb/init.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    networks:
      - backend
    environment:
      PMA_HOST: mysql     
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: 1234
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./mysql/dbdata:/var/dbdata/  


networks:
  frontend:
  backend:
