version: "3"
name: "php7"

services:
    www:
        build: .
        container_name: www
        depends_on:
            - db
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/html/
        networks:
            - default
        links:
            - db:mysql
    db:
        image: mysql
        container_name: db
        ports:
            - "3307:3306"
        environment:
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        ports:
            - 8002:80
        environment:
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        networks:
            - default
volumes:
    persistent:
