version: "3.2"
services:

  php:
    build: './php/'
    container_name: 'php'
    networks:
      - backend
    volumes:
      - ./../bbpl:/var/www/html/

  apache:
    build: './apache/'
    container_name: 'apache'
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./../bbpl:/var/www/html/

  mysql:
    build: './mysql/'
    restart: always
    container_name: 'mysql'
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/dbdata:/var/lib/mysql/  
    environment:
      MYSQL_DATABASE: bbpl_payments_local
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    networks:
      - backend
    environment:
      PMA_HOST: mysql     
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: 1234
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./mysql/dbdata:/var/dbdata/  


networks:
  frontend:
  backend:
